FROM mdillon/postgis
# Source of TIGER data
VOLUME /gisdata
ADD src/main/sh/stage.sh  /docker-entrypoint-initdb.d/
ADD src/main/sql/*  /docker-entrypoint-initdb.d/
# Make sure these exist. Runtime will append to zdata.sql
RUN mkdir -m 777 /stage && \
    touch /docker-entrypoint-initdb.d/zdata.sql && \
    chmod 666 /docker-entrypoint-initdb.d/zdata.sql
