FROM mdillon/postgis
# Source of TIGER data
VOLUME /gisdata
ENV SCRIPTS=/docker-entrypoint-initdb.d/ STAGE=/stage
ADD src/main/sh/stage.sh ${SCRIPTS}
ADD src/main/sql/* ${SCRIPTS}
# Make sure these exist. Runtime will append to zdata.sql
RUN mkdir -m 777 ${STAGE} && \
    touch ${SCRIPTS}zdata.sql && \
    chmod 666 ${SCRIPTS}zdata.sql
