FROM mdillon/postgis
# Source of TIGER data
VOLUME /gisdata
ENV SCRIPTS=/docker-entrypoint-initdb.d/ STAGE=/stage
RUN mkdir ${STAGE} && chmod 777 ${STAGE}
ADD src/main/sh/stage.sh ${SCRIPTS}
ADD src/main/sql/* ${SCRIPTS}
